/**
 * Module: Failure Analysis & Auto-Remediation
 * Description: Analyzes tool execution failures and generates self-fix tasks.
 */

import { logger } from '../utils/logger';

export interface ErrorContext {
  toolName: string;
  errorMessage: string;
  parameters?: Record<string, any>;
  timestamp: string;
  stackTrace?: string;
}

export interface RemediationTask {
  type: 'fix_issue';
  title: string;
  description: string;
  priority: 'high' | 'medium' | 'low';
  metadata: {
    originalTool: string;
    errorCategory: string;
    confidenceScore: number;
    timestamp: string;
    originalContext: ErrorContext;
  };
  autoGenerated: boolean;
}

export class FailureAnalyzer {
  private errorPatterns: Record<string, string[]> = {
    rate_limit: ['rate limit', 'too many requests', '429'],
    auth_error: ['unauthorized', '401', 'invalid token', 'authentication failed'],
    timeout: ['timeout', 'timed out', 'connection reset'],
    context_length: ['context length', 'token limit', 'maximum context'],
    syntax_error: ['syntax error', 'invalid json', 'parse error'],
    network_error: ['network', 'connection refused', 'dns'],
    permission_error: ['permission denied', 'access denied', 'forbidden', '403'],
  };

  /**
   * Analyzes an error message to determine the root cause and suggests a fix.
   * Returns a task definition if a fix is possible.
   */
  public analyzeError(errorData: ErrorContext): RemediationTask | null {
    const errorLower = errorData.errorMessage.toLowerCase();
    let category = 'unknown';
    let confidence = 0.5;
    let suggestedAction = '';

    // Pattern matching for known errors
    for (const [cat, patterns] of Object.entries(this.errorPatterns)) {
      for (const pattern of patterns) {
        if (errorLower.includes(pattern)) {
          category = cat;
          confidence = 0.85;
          suggestedAction = this.getSuggestedAction(cat, errorData);
          break;
        }
      }
      if (category !== 'unknown') break;
    }

    if (category === 'unknown') {
      suggestedAction = `Investigate the error logs for ${errorData.toolName} and retry with modified parameters.`;
      confidence = 0.5;
    }

    const remediationTask: RemediationTask = {
      type: 'fix_issue',
      title: `Fix ${category.replace('_', ' ')} in ${errorData.toolName}`,
      description: `Error detected: ${errorData.errorMessage}\nSuggested action: ${suggestedAction}`,
      priority: confidence > 0.7 ? 'high' : 'medium',
      metadata: {
        originalTool: errorData.toolName,
        errorCategory: category,
        confidenceScore: confidence,
        timestamp: new Date().toISOString(),
        originalContext: errorData,
      },
      autoGenerated: true,
    };

    logger.info(
      `Failure Analysis: Detected '${category}' in ${errorData.toolName}. Confidence: ${confidence}`
    );

    return remediationTask;
  }

  /**
   * Gets suggested action based on error category
   */
  private getSuggestedAction(category: string, errorData: ErrorContext): string {
    const actions: Record<string, string> = {
      rate_limit: 'Wait for 60 seconds and retry the request with exponential backoff.',
      auth_error: 'Refresh authentication tokens or check API key validity.',
      timeout: 'Increase timeout settings or check network connectivity. Retry with smaller payload.',
      context_length: 'Summarize previous conversation history or truncate input data.',
      syntax_error: 'Validate JSON structure before sending. Use a JSON repair library.',
      network_error: 'Check network connectivity and DNS settings. Retry with connection pooling.',
      permission_error: 'Verify API permissions and scope. Update credentials if necessary.',
    };

    return (
      actions[category] || 'Manual investigation required. Check service status and logs.'
    );
  }

  /**
   * Creates a structured task for the task planner
   */
  public createFixTask(errorData: ErrorContext): RemediationTask | null {
    return this.analyzeError(errorData);
  }
}
