import { useEffect, useState } from 'react';
import { api } from '../lib/api';

interface DailyPlan {
  date: string;
  goals: string[];
  priorities: string[];
  scheduledTasks: Array<{
    time?: string;
    description: string;
    priority: number;
  }>;
  reflections?: string;
  createdAt: number;
}

interface EveningReflection {
  date: string;
  accomplishments: string[];
  failures: Array<{
    description: string;
    rootCause: string;
    lesson: string;
    actionItem?: string;
  }>;
  insights: string[];
  tomorrowFocus: string[];
  mood?: "productive" | "neutral" | "challenging";
  createdAt: number;
}

interface HealthMetrics {
  timestamp: string;
  tokenUsage: {
    total: number;
    input: number;
    output: number;
  };
  toolExecution: {
    total: number;
    successful: number;
    failed: number;
    successRate: number;
  };
  responseTime: {
    averageMs: number;
    p95Ms: number;
    p99Ms: number;
  };
}

interface HealthAlert {
  id: string;
  severity: 'critical' | 'warning' | 'info';
  metric: string;
  currentValue: number;
  threshold: number;
  message: string;
  timestamp: string;
  suggestedAction?: string;
}

interface RemediationTask {
  type: 'fix_issue';
  title: string;
  description: string;
  priority: 'high' | 'medium' | 'low';
  metadata: {
    originalTool: string;
    errorCategory: string;
    confidenceScore: number;
    timestamp: string;
  };
  autoGenerated: boolean;
}

interface DashboardData {
  todayPlan?: DailyPlan;
  todayProgress: {
    completedTasks: number;
    totalTasks: number;
    goalsProgress: number;
  };
  recentFailures: Array<{
    timestamp: number;
    context: string;
    errorType: string;
    severity: string;
    description: string;
  }>;
  streaks: {
    daysActive: number;
    plansCreated: number;
    reflectionsCompleted: number;
  };
  health: {
    errorRate: number;
    successRate: number;
    avgResponseTime?: number;
  };
}

interface HealthStatus {
  status: 'healthy' | 'degraded' | 'critical';
  activeAlerts: number;
  criticalAlerts: number;
  latestMetrics: HealthMetrics | null;
}

export function Autonomous() {
  const [dashboardData, setDashboardData] = useState<DashboardData | null>(null);
  const [currentPlan, setCurrentPlan] = useState<DailyPlan | null>(null);
  const [currentReflection, setCurrentReflection] = useState<EveningReflection | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [generatingPlan, setGeneratingPlan] = useState(false);
  const [generatingReflection, setGeneratingReflection] = useState(false);
  
  // Phase 2: Health & Auto-Fix states
  const [healthStatus, setHealthStatus] = useState<HealthStatus | null>(null);
  const [healthAlerts, setHealthAlerts] = useState<HealthAlert[]>([]);
  const [autoFixes, setAutoFixes] = useState<RemediationTask[]>([]);
  const [metricsHistory, setMetricsHistory] = useState<HealthMetrics[]>([]);

  useEffect(() => {
    loadDashboardData();
    loadHealthData();
  }, []);

  async function loadDashboardData() {
    try {
      setLoading(true);
      const response = await api.get('/api/autonomous/dashboard');
      setDashboardData(response.data);
      setError(null);
    } catch (err) {
      setError('Failed to load dashboard data');
      console.error(err);
    } finally {
      setLoading(false);
    }
  }

  async function loadHealthData() {
    try {
      // Load health status
      const statusResponse = await api.get('/api/autonomous/health/status');
      setHealthStatus(statusResponse.data);

      // Load alerts
      const alertsResponse = await api.get('/api/autonomous/health/alerts?limit=10');
      setHealthAlerts(alertsResponse.data.alerts || []);

      // Load metrics history
      const historyResponse = await api.get('/api/autonomous/health/history?limit=20');
      setMetricsHistory(historyResponse.data.history || []);

      // Load auto-fix tasks
      const tasksResponse = await api.get('/api/autonomous/tasks?status=pending&limit=20');
      const fixTasks = (tasksResponse.data.tasks || []).filter((t: any) => t.payload?.type === 'fix_issue');
      setAutoFixes(fixTasks.map((t: any) => t.payload));
    } catch (err) {
      console.error('Failed to load health data:', err);
    }
  }

  async function handleGeneratePlan() {
    try {
      setGeneratingPlan(true);
      const response = await api.post('/api/autonomous/plan/daily', {});
      setCurrentPlan(response.data.plan);
      await loadDashboardData();
    } catch (err) {
      setError('Failed to generate daily plan');
      console.error(err);
    } finally {
      setGeneratingPlan(false);
    }
  }

  async function handleGenerateReflection() {
    try {
      setGeneratingReflection(true);
      const response = await api.post('/api/autonomous/reflection/evening', {});
      setCurrentReflection(response.data.reflection);
      await loadDashboardData();
    } catch (err) {
      setError('Failed to generate evening reflection');
      console.error(err);
    } finally {
      setGeneratingReflection(false);
    }
  }

  if (loading) {
    return <div className="loading">Loading autonomous dashboard...</div>;
  }

  return (
    <div className="autonomous-root">
      <div className="header">
        <h1>🤖 Autonomous Agent Control</h1>
        <p>Daily planning, reflection, and self-monitoring</p>
      </div>

      {error && (
        <div className="alert error" style={{ marginBottom: '14px' }}>
          {error}
          <button onClick={() => setError(null)} style={{ marginLeft: '10px', padding: '2px 8px', fontSize: '12px' }}>Dismiss</button>
        </div>
      )}

      {/* Quick Actions */}
      <div className="card" style={{ marginBottom: '20px' }}>
        <h2>Quick Actions</h2>
        <div style={{ display: 'flex', gap: '10px', marginTop: '15px' }}>
          <button 
            onClick={handleGeneratePlan} 
            disabled={generatingPlan}
            className="btn primary"
          >
            {generatingPlan ? 'Generating...' : '📅 Generate Daily Plan'}
          </button>
          <button 
            onClick={handleGenerateReflection} 
            disabled={generatingReflection}
            className="btn secondary"
          >
            {generatingReflection ? 'Generating...' : '🌙 Generate Evening Reflection'}
          </button>
          <button onClick={() => { loadDashboardData(); loadHealthData(); }} className="btn">
            🔄 Refresh Dashboard
          </button>
        </div>
      </div>

      {/* Phase 2: Health Status Banner */}
      {healthStatus && (
        <div className={`card ${healthStatus.status === 'critical' ? 'alert-error' : healthStatus.status === 'degraded' ? 'alert-warning' : ''}`} style={{ marginBottom: '20px' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <div>
              <h3>
                {healthStatus.status === 'healthy' && '✅ System Healthy'}
                {healthStatus.status === 'degraded' && '⚠️ System Degraded'}
                {healthStatus.status === 'critical' && '🚨 Critical Issues Detected'}
              </h3>
              <p>
                Active Alerts: {healthStatus.activeAlerts} | Critical: {healthStatus.criticalAlerts}
              </p>
            </div>
            <button onClick={loadHealthData} className="btn">Refresh Health</button>
          </div>
        </div>
      )}

      {/* Health Metrics */}
      {dashboardData && (
        <div className="grid-3" style={{ marginBottom: '20px' }}>
          <div className="card">
            <h3>📊 Today's Progress</h3>
            <div className="stat-large">
              {dashboardData.todayProgress.completedTasks}/{dashboardData.todayProgress.totalTasks}
            </div>
            <p>Tasks Completed</p>
            <div className="progress-bar" style={{ marginTop: '10px' }}>
              <div 
                className="progress-fill" 
                style={{ width: `${dashboardData.todayProgress.goalsProgress}%` }}
              />
            </div>
            <p style={{ fontSize: '12px', marginTop: '5px' }}>
              {dashboardData.todayProgress.goalsProgress}% of goals
            </p>
          </div>

          <div className="card">
            <h3>❤️ Health Status</h3>
            <div className="stat-large" style={{ color: dashboardData.health.successRate >= 80 ? '#4caf50' : dashboardData.health.successRate >= 50 ? '#ff9800' : '#f44336' }}>
              {dashboardData.health.successRate}%
            </div>
            <p>Success Rate</p>
            <p style={{ fontSize: '12px', marginTop: '5px' }}>
              Error Rate: {dashboardData.health.errorRate}%
            </p>
            {dashboardData.health.avgResponseTime && (
              <p style={{ fontSize: '12px' }}>
                Avg Response: {dashboardData.health.avgResponseTime}ms
              </p>
            )}
          </div>

          <div className="card">
            <h3>🔥 Streaks</h3>
            <div className="stat-row">
              <span>Days Active:</span>
              <strong>{dashboardData.streaks.daysActive}</strong>
            </div>
            <div className="stat-row">
              <span>Plans Created:</span>
              <strong>{dashboardData.streaks.plansCreated}</strong>
            </div>
            <div className="stat-row">
              <span>Reflections:</span>
              <strong>{dashboardData.streaks.reflectionsCompleted}</strong>
            </div>
          </div>
        </div>
      )}

      {/* Today's Plan */}
      <div className="card" style={{ marginBottom: '20px' }}>
        <h2>📅 Today's Plan</h2>
        {currentPlan || dashboardData?.todayPlan ? (
          <div>
            {(currentPlan || dashboardData?.todayPlan)!.goals.length > 0 && (
              <div style={{ marginBottom: '15px' }}>
                <h3>Goals</h3>
                <ul>
                  {(currentPlan || dashboardData?.todayPlan)!.goals.map((goal, idx) => (
                    <li key={idx}>{goal}</li>
                  ))}
                </ul>
              </div>
            )}
            {(currentPlan || dashboardData?.todayPlan)!.priorities.length > 0 && (
              <div style={{ marginBottom: '15px' }}>
                <h3>Priorities</h3>
                <ul>
                  {(currentPlan || dashboardData?.todayPlan)!.priorities.map((priority, idx) => (
                    <li key={idx}>{priority}</li>
                  ))}
                </ul>
              </div>
            )}
            {(currentPlan || dashboardData?.todayPlan)!.scheduledTasks.length > 0 && (
              <div>
                <h3>Scheduled Tasks</h3>
                <table className="data-table">
                  <thead>
                    <tr>
                      <th>Time</th>
                      <th>Task</th>
                      <th>Priority</th>
                    </tr>
                  </thead>
                  <tbody>
                    {(currentPlan || dashboardData?.todayPlan)!.scheduledTasks.map((task, idx) => (
                      <tr key={idx}>
                        <td>{task.time || 'Anytime'}</td>
                        <td>{task.description}</td>
                        <td>P{task.priority}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        ) : (
          <p>No plan generated yet. Click "Generate Daily Plan" to create one.</p>
        )}
      </div>

      {/* Recent Failures */}
      {dashboardData && dashboardData.recentFailures.length > 0 && (
        <div className="card" style={{ marginBottom: '20px' }}>
          <h2>⚠️ Recent Failures</h2>
          <table className="data-table">
            <thead>
              <tr>
                <th>Type</th>
                <th>Severity</th>
                <th>Description</th>
                <th>Context</th>
              </tr>
            </thead>
            <tbody>
              {dashboardData.recentFailures.slice(0, 10).map((failure, idx) => (
                <tr key={idx} style={{ 
                  backgroundColor: failure.severity === 'critical' ? '#ffebee' : 
                                   failure.severity === 'high' ? '#fff3e0' : 
                                   failure.severity === 'medium' ? '#fff8e1' : 'transparent' 
                }}>
                  <td>{failure.errorType}</td>
                  <td>
                    <span className={`badge badge-${failure.severity}`}>
                      {failure.severity}
                    </span>
                  </td>
                  <td>{failure.description}</td>
                  <td style={{ maxWidth: '300px', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                    {failure.context}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {/* Phase 2: Health Alerts */}
      {healthAlerts.length > 0 && (
        <div className="card" style={{ marginBottom: '20px' }}>
          <h2>🚨 Health Alerts</h2>
          <table className="data-table">
            <thead>
              <tr>
                <th>Severity</th>
                <th>Metric</th>
                <th>Message</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              {healthAlerts.map((alert) => (
                <tr key={alert.id} style={{ 
                  backgroundColor: alert.severity === 'critical' ? '#ffebee' : 
                                   alert.severity === 'warning' ? '#fff3e0' : '#e3f2fd'
                }}>
                  <td>
                    <span className={`badge badge-${alert.severity}`}>
                      {alert.severity}
                    </span>
                  </td>
                  <td>{alert.metric}</td>
                  <td>{alert.message}</td>
                  <td>{alert.suggestedAction || '-'}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {/* Phase 2: Auto-Fix Tasks */}
      {autoFixes.length > 0 && (
        <div className="card" style={{ marginBottom: '20px' }}>
          <h2>🔧 Auto-Generated Fixes</h2>
          <p style={{ fontSize: '14px', color: '#666', marginBottom: '15px' }}>
            These tasks were automatically created by the agent to fix detected issues.
          </p>
          <table className="data-table">
            <thead>
              <tr>
                <th>Priority</th>
                <th>Issue</th>
                <th>Tool</th>
                <th>Confidence</th>
                <th>Description</th>
              </tr>
            </thead>
            <tbody>
              {autoFixes.map((fix, idx) => (
                <tr key={idx}>
                  <td>
                    <span className={`badge badge-${fix.priority}`}>
                      {fix.priority}
                    </span>
                  </td>
                  <td>{fix.metadata.errorCategory}</td>
                  <td>{fix.metadata.originalTool}</td>
                  <td>{(fix.metadata.confidenceScore * 100).toFixed(0)}%</td>
                  <td style={{ maxWidth: '300px', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                    {fix.description}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {/* Evening Reflection */}
      {currentReflection && (
        <div className="card" style={{ marginBottom: '20px' }}>
          <h2>🌙 Evening Reflection - {currentReflection.date}</h2>
          <div style={{ marginBottom: '15px' }}>
            <h3>Accomplishments</h3>
            <ul>
              {currentReflection.accomplishments.map((acc, idx) => (
                <li key={idx}>✅ {acc}</li>
              ))}
            </ul>
          </div>
          
          {currentReflection.failures.length > 0 && (
            <div style={{ marginBottom: '15px' }}>
              <h3>Failures & Lessons</h3>
              {currentReflection.failures.map((failure, idx) => (
                <div key={idx} style={{ 
                  padding: '10px', 
                  marginBottom: '10px', 
                  backgroundColor: '#fff3e0', 
                  borderRadius: '4px' 
                }}>
                  <p><strong>Issue:</strong> {failure.description}</p>
                  <p><strong>Root Cause:</strong> {failure.rootCause}</p>
                  <p><strong>Lesson:</strong> {failure.lesson}</p>
                  {failure.actionItem && (
                    <p><strong>Action:</strong> {failure.actionItem}</p>
                  )}
                </div>
              ))}
            </div>
          )}

          {currentReflection.insights.length > 0 && (
            <div style={{ marginBottom: '15px' }}>
              <h3>Insights</h3>
              <ul>
                {currentReflection.insights.map((insight, idx) => (
                  <li key={idx}>💡 {insight}</li>
                ))}
              </ul>
            </div>
          )}

          {currentReflection.tomorrowFocus.length > 0 && (
            <div>
              <h3>Focus for Tomorrow</h3>
              <ul>
                {currentReflection.tomorrowFocus.map((focus, idx) => (
                  <li key={idx}>🎯 {focus}</li>
                ))}
              </ul>
            </div>
          )}

          {currentReflection.mood && (
            <div style={{ marginTop: '15px', paddingTop: '15px', borderTop: '1px solid #eee' }}>
              <strong>Mood:</strong> 
              <span style={{ 
                marginLeft: '10px', 
                padding: '4px 12px', 
                borderRadius: '12px',
                backgroundColor: currentReflection.mood === 'productive' ? '#e8f5e9' : 
                                 currentReflection.mood === 'challenging' ? '#ffebee' : '#e3f2fd'
              }}>
                {currentReflection.mood}
              </span>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// =====================
// PHASE 3: GOAL MANAGEMENT TYPES & COMPONENTS
// =====================

interface Goal {
  id: string;
  title: string;
  description?: string;
  level: 'long_term' | 'mid_term' | 'short_term';
  status: 'active' | 'completed' | 'paused' | 'blocked' | 'archived';
  parentId: string | null;
  priority: number;
  deadline: string | null;
  createdAt: string;
  updatedAt: string;
  metrics: {
    progress: number;
    completedSubtasks: number;
    totalSubtasks: number;
  };
}

interface GoalStats {
  total: number;
  byLevel: Record<string, number>;
  byStatus: Record<string, number>;
  avgProgress: number;
}

interface GoalTreeNode extends Goal {
  children: GoalTreeNode[];
}

// Add to component state
const [goals, setGoals] = useState<Goal[]>([]);
const [goalTree, setGoalTree] = useState<GoalTreeNode[]>([]);
const [goalStats, setGoalStats] = useState<GoalStats | null>(null);
const [selectedGoal, setSelectedGoal] = useState<Goal | null>(null);
const [isDecomposing, setIsDecomposing] = useState(false);
const [showCreateGoal, setShowCreateGoal] = useState(false);

// Fetch goals on mount
useEffect(() => {
  loadGoals();
  loadGoalTree();
  loadGoalStats();
}, []);

const loadGoals = async () => {
  try {
    const data = await api.get('/autonomous/goals');
    setGoals(data.goals || []);
  } catch (error) {
    console.error('Failed to load goals:', error);
  }
};

const loadGoalTree = async () => {
  try {
    const data = await api.get('/autonomous/goals/tree');
    setGoalTree(data.tree || []);
  } catch (error) {
    console.error('Failed to load goal tree:', error);
  }
};

const loadGoalStats = async () => {
  try {
    const data = await api.get('/autonomous/goals/stats');
    setGoalStats(data.stats || null);
  } catch (error) {
    console.error('Failed to load goal stats:', error);
  }
};

const handleCreateGoal = async (goalData: Partial<Goal>) => {
  try {
    await api.post('/autonomous/goals', goalData);
    await loadGoals();
    await loadGoalTree();
    await loadGoalStats();
    setShowCreateGoal(false);
  } catch (error) {
    console.error('Failed to create goal:', error);
    alert('Failed to create goal');
  }
};

const handleDecomposeGoal = async (goalId: string) => {
  if (!selectedGoal) return;
  
  setIsDecomposing(true);
  try {
    await api.post(`/autonomous/goals/${goalId}/decompose`, {
      targetLevel: 'short_term',
      maxDepth: 2
    });
    await loadGoals();
    await loadGoalTree();
    alert('Goal decomposed successfully!');
  } catch (error) {
    console.error('Failed to decompose goal:', error);
    alert('Failed to decompose goal');
  } finally {
    setIsDecomposing(false);
  }
};

const handleUpdateGoalStatus = async (goalId: string, status: string) => {
  try {
    await api.put(`/autonomous/goals/${goalId}/status`, { status });
    await loadGoals();
    await loadGoalTree();
  } catch (error) {
    console.error('Failed to update goal status:', error);
  }
};

const handleUpdateGoalProgress = async (goalId: string, progress: number) => {
  try {
    await api.put(`/autonomous/goals/${goalId}/progress`, { progress });
    await loadGoals();
    await loadGoalTree();
  } catch (error) {
    console.error('Failed to update goal progress:', error);
  }
};

const handleDeleteGoal = async (goalId: string) => {
  if (!confirm('Are you sure? This will delete all sub-goals as well.')) return;
  
  try {
    await api.delete(`/autonomous/goals/${goalId}`);
    await loadGoals();
    await loadGoalTree();
    setSelectedGoal(null);
  } catch (error) {
    console.error('Failed to delete goal:', error);
  }
};

const getLevelColor = (level: string) => {
  switch (level) {
    case 'long_term': return '#1976d2';
    case 'mid_term': return '#388e3c';
    case 'short_term': return '#f57c00';
    default: return '#757575';
  }
};

const getStatusColor = (status: string) => {
  switch (status) {
    case 'active': return '#4caf50';
    case 'completed': return '#2e7d32';
    case 'paused': return '#ff9800';
    case 'blocked': return '#f44336';
    case 'archived': return '#9e9e9e';
    default: return '#757575';
  }
};

// Recursive tree node component
const GoalTreeNodeComponent: React.FC<{
  node: GoalTreeNode;
  depth: number;
  onSelect: (goal: Goal) => void;
  selectedId?: string;
}> = ({ node, depth, onSelect, selectedId }) => {
  const [expanded, setExpanded] = useState(true);
  const hasChildren = node.children && node.children.length > 0;
  
  return (
    <div style={{ marginLeft: depth * 20 }}>
      <div
        onClick={() => onSelect(node)}
        style={{
          padding: '10px',
          marginBottom: '5px',
          backgroundColor: selectedId === node.id ? '#e3f2fd' : '#f5f5f5',
          borderRadius: '4px',
          cursor: 'pointer',
          borderLeft: `4px solid ${getLevelColor(node.level)}`,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between'
        }}
      >
        <div style={{ flex: 1 }}>
          <div style={{ fontWeight: 'bold', marginBottom: '4px' }}>{node.title}</div>
          <div style={{ fontSize: '12px', color: '#666' }}>
            <span style={{ 
              backgroundColor: getStatusColor(node.status),
              color: 'white',
              padding: '2px 8px',
              borderRadius: '10px',
              marginRight: '8px'
            }}>
              {node.status}
            </span>
            <span>Priority: {node.priority}/10</span>
            {node.deadline && <span> | Due: {new Date(node.deadline).toLocaleDateString()}</span>}
          </div>
          <div style={{ marginTop: '5px' }}>
            <div style={{ fontSize: '11px', color: '#999', marginBottom: '2px' }}>
              Progress: {node.metrics.progress}% ({node.metrics.completedSubtasks}/{node.metrics.totalSubtasks})
            </div>
            <div style={{ width: '100%', height: '6px', backgroundColor: '#e0e0e0', borderRadius: '3px' }}>
              <div style={{
                width: `${node.metrics.progress}%`,
                height: '100%',
                backgroundColor: getLevelColor(node.level),
                borderRadius: '3px',
                transition: 'width 0.3s ease'
              }} />
            </div>
          </div>
        </div>
        
        {hasChildren && (
          <button
            onClick={(e) => { e.stopPropagation(); setExpanded(!expanded); }}
            style={{
              background: 'none',
              border: 'none',
              fontSize: '16px',
              cursor: 'pointer',
              padding: '4px 8px'
            }}
          >
            {expanded ? '▼' : '▶'}
          </button>
        )}
      </div>
      
      {expanded && hasChildren && (
        <div>
          {node.children.map(child => (
            <GoalTreeNodeComponent
              key={child.id}
              node={child}
              depth={depth + 1}
              onSelect={onSelect}
              selectedId={selectedId}
            />
          ))}
        </div>
      )}
    </div>
  );
};

// Create Goal Form Component
const CreateGoalForm: React.FC<{
  onSubmit: (data: any) => void;
  onCancel: () => void;
  parentGoal?: Goal | null;
}> = ({ onSubmit, onCancel, parentGoal }) => {
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [level, setLevel] = useState<'long_term' | 'mid_term' | 'short_term'>('short_term');
  const [priority, setPriority] = useState(5);
  const [deadline, setDeadline] = useState('');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onSubmit({
      title,
      description,
      level,
      priority,
      deadline: deadline || null,
      parentId: parentGoal?.id || null
    });
  };

  return (
    <div style={{
      position: 'fixed',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(0,0,0,0.5)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 1000
    }}>
      <div style={{
        backgroundColor: 'white',
        padding: '30px',
        borderRadius: '8px',
        width: '500px',
        maxWidth: '90%'
      }}>
        <h2 style={{ marginTop: 0 }}>
          {parentGoal ? `Create Sub-Goal for "${parentGoal.title}"` : 'Create New Goal'}
        </h2>
        
        <form onSubmit={handleSubmit}>
          <div style={{ marginBottom: '15px' }}>
            <label style={{ display: 'block', marginBottom: '5px', fontWeight: 'bold' }}>Title *</label>
            <input
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              required
              style={{ width: '100%', padding: '8px', boxSizing: 'border-box' }}
            />
          </div>
          
          <div style={{ marginBottom: '15px' }}>
            <label style={{ display: 'block', marginBottom: '5px', fontWeight: 'bold' }}>Description</label>
            <textarea
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              rows={3}
              style={{ width: '100%', padding: '8px', boxSizing: 'border-box' }}
            />
          </div>
          
          <div style={{ marginBottom: '15px' }}>
            <label style={{ display: 'block', marginBottom: '5px', fontWeight: 'bold' }}>Level *</label>
            <select
              value={level}
              onChange={(e) => setLevel(e.target.value as any)}
              style={{ width: '100%', padding: '8px' }}
            >
              <option value="long_term">🎯 Long-term (Strategy)</option>
              <option value="mid_term">📋 Mid-term (Project)</option>
              <option value="short_term">✅ Short-term (Task)</option>
            </select>
          </div>
          
          <div style={{ marginBottom: '15px' }}>
            <label style={{ display: 'block', marginBottom: '5px', fontWeight: 'bold' }}>Priority (1-10)</label>
            <input
              type="number"
              min="1"
              max="10"
              value={priority}
              onChange={(e) => setPriority(parseInt(e.target.value))}
              style={{ width: '100%', padding: '8px', boxSizing: 'border-box' }}
            />
          </div>
          
          <div style={{ marginBottom: '20px' }}>
            <label style={{ display: 'block', marginBottom: '5px', fontWeight: 'bold' }}>Deadline</label>
            <input
              type="date"
              value={deadline}
              onChange={(e) => setDeadline(e.target.value)}
              style={{ width: '100%', padding: '8px', boxSizing: 'border-box' }}
            />
          </div>
          
          <div style={{ display: 'flex', gap: '10px', justifyContent: 'flex-end' }}>
            <button type="button" onClick={onCancel} style={{
              padding: '10px 20px',
              border: '1px solid #ddd',
              backgroundColor: 'white',
              borderRadius: '4px',
              cursor: 'pointer'
            }}>
              Cancel
            </button>
            <button type="submit" style={{
              padding: '10px 20px',
              border: 'none',
              backgroundColor: '#1976d2',
              color: 'white',
              borderRadius: '4px',
              cursor: 'pointer'
            }}>
              Create Goal
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

// In the main render, add new sections before the closing div

// ============================================
// Phase 4: Multi-Agent System UI Components
// ============================================

interface AgentStats {
  name: string;
  role: string;
  totalTasks: number;
  completedTasks: number;
  failedTasks: number;
  pendingTasks: number;
}

interface TaskAssignment {
  taskId: string;
  assignedTo: string;
  assignedBy: string;
  role: string;
  priority: string;
  status: string;
  dependencies?: string[];
}

interface AgentMessage {
  id: string;
  fromAgent: string;
  toAgent?: string;
  role: string;
  content: string;
  timestamp: string;
  messageType: string;
  taskId?: string;
}

const MultiAgentPanel = () => {
  const [agents, setAgents] = useState<Record<string, AgentStats>>({});
  const [activeAssignments, setActiveAssignments] = useState<TaskAssignment[]>([]);
  const [messages, setMessages] = useState<AgentMessage[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedAgent, setSelectedAgent] = useState<string | null>(null);
  const [messageText, setMessageText] = useState('');
  const [consensusSession, setConsensusSession] = useState<any>(null);

  useEffect(() => {
    loadMultiAgentData();
    const interval = setInterval(loadMultiAgentData, 10000); // Poll every 10s
    return () => clearInterval(interval);
  }, []);

  const loadMultiAgentData = async () => {
    try {
      setLoading(true);
      
      // Load agents
      const agentsRes = await api.get('/api/autonomous/agents');
      setAgents(agentsRes.agents || {});
      
      // Load active assignments
      const tasksRes = await api.get('/api/autonomous/agents/tasks/active');
      setActiveAssignments(tasksRes.assignments || []);
      
      // Load messages
      const msgsRes = await api.get('/api/autonomous/agents/messages');
      setMessages(msgsRes.messages || []);
    } catch (error) {
      console.error('Failed to load multi-agent data:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleSendMessage = async () => {
    if (!selectedAgent || !messageText.trim()) return;
    
    try {
      await api.post(`/api/autonomous/agents/${selectedAgent}/message`, {
        fromAgent: 'user',
        content: messageText,
        messageType: 'request',
        metadata: { from: 'webui' }
      });
      setMessageText('');
      await loadMultiAgentData();
    } catch (error) {
      alert('Failed to send message');
    }
  };

  const handleDecomposeTask = async () => {
    const taskId = prompt('Enter task ID:');
    const description = prompt('Enter task description:');
    if (!taskId || !description) return;

    try {
      await api.post('/api/autonomous/agents/task/decompose', {
        taskId,
        description
      });
      alert('Task decomposed and assigned!');
      await loadMultiAgentData();
    } catch (error) {
      alert('Failed to decompose task');
    }
  };

  const handleInitiateConsensus = async () => {
    const taskId = prompt('Enter task ID for consensus:');
    const roles = prompt('Enter required roles (comma-separated, e.g., critic,coder):');
    if (!taskId || !roles) return;

    try {
      const requiredRoles = roles.split(',').map(r => r.trim());
      const res = await api.post('/api/autonomous/agents/consensus/initiate', {
        taskId,
        requiredRoles
      });
      setConsensusSession({ sessionId: res.sessionId, taskId });
      alert(`Consensus session initiated: ${res.sessionId}`);
    } catch (error) {
      alert('Failed to initiate consensus');
    }
  };

  const handleCastVote = async () => {
    if (!consensusSession) return;
    
    const voterId = prompt('Your agent ID:');
    const vote = prompt('Vote (approve/reject/abstain):');
    const reasoning = prompt('Reasoning:');
    const confidence = prompt('Confidence (0-1):', '0.8');
    
    if (!voterId || !vote || !reasoning || !confidence) return;

    try {
      await api.post(`/api/autonomous/agents/consensus/${consensusSession.sessionId}/vote`, {
        voterId,
        vote,
        reasoning,
        confidence: parseFloat(confidence)
      });
      alert('Vote cast successfully!');
    } catch (error) {
      alert('Failed to cast vote');
    }
  };

  if (loading) return <div>Loading multi-agent system...</div>;

  const agentList = Object.entries(agents);

  return (
    <div style={{ padding: '20px' }}>
      <h2>🤖 Multi-Agent Coordination</h2>
      
      {/* Agent Stats Grid */}
      <div style={{ 
        display: 'grid', 
        gridTemplateColumns: 'repeat(auto-fill, minmax(250px, 1fr))', 
        gap: '15px',
        marginBottom: '30px'
      }}>
        {agentList.map(([id, stats]) => (
          <div key={id} style={{
            border: selectedAgent === id ? '2px solid #1976d2' : '1px solid #ddd',
            borderRadius: '8px',
            padding: '15px',
            backgroundColor: selectedAgent === id ? '#e3f2fd' : 'white',
            cursor: 'pointer'
          }} onClick={() => setSelectedAgent(id)}>
            <h3 style={{ margin: '0 0 10px 0' }}>{stats.name}</h3>
            <p style={{ margin: '5px 0', color: '#666' }}>{stats.role}</p>
            <div style={{ fontSize: '13px' }}>
              <div>✅ Completed: {stats.completedTasks}</div>
              <div>⏳ Pending: {stats.pendingTasks}</div>
              <div>❌ Failed: {stats.failedTasks}</div>
              <div>📊 Total: {stats.totalTasks}</div>
            </div>
          </div>
        ))}
      </div>

      {/* Actions */}
      <div style={{ 
        display: 'flex', 
        gap: '10px', 
        marginBottom: '20px',
        flexWrap: 'wrap'
      }}>
        <button onClick={handleDecomposeTask} className="btn">
          🔨 Decompose Task
        </button>
        <button onClick={handleInitiateConsensus} className="btn">
          🗳️ Initiate Consensus
        </button>
        {consensusSession && (
          <button onClick={handleCastVote} className="btn">
            ✍️ Cast Vote
          </button>
        )}
        <button onClick={loadMultiAgentData} className="btn">
          🔄 Refresh
        </button>
      </div>

      {/* Message Interface */}
      {selectedAgent && (
        <div style={{ 
          border: '1px solid #ddd', 
          borderRadius: '8px', 
          padding: '15px',
          marginBottom: '20px'
        }}>
          <h3>💬 Send Message to {agents[selectedAgent]?.name}</h3>
          <textarea
            value={messageText}
            onChange={(e) => setMessageText(e.target.value)}
            placeholder="Type your message..."
            rows={3}
            style={{ width: '100%', padding: '8px', marginBottom: '10px' }}
          />
          <button onClick={handleSendMessage} className="btn btn-primary">
            Send Message
          </button>
        </div>
      )}

      {/* Active Assignments */}
      <div style={{ marginBottom: '20px' }}>
        <h3>📋 Active Task Assignments</h3>
        {activeAssignments.length === 0 ? (
          <p>No active assignments</p>
        ) : (
          <table style={{ width: '100%', borderCollapse: 'collapse' }}>
            <thead>
              <tr style={{ backgroundColor: '#f5f5f5' }}>
                <th style={thStyle}>Task ID</th>
                <th style={thStyle}>Agent</th>
                <th style={thStyle}>Role</th>
                <th style={thStyle}>Priority</th>
                <th style={thStyle}>Status</th>
              </tr>
            </thead>
            <tbody>
              {activeAssignments.map(task => (
                <tr key={task.taskId}>
                  <td style={tdStyle}>{task.taskId}</td>
                  <td style={tdStyle}>{task.assignedTo}</td>
                  <td style={tdStyle}>{task.role}</td>
                  <td style={tdStyle}>
                    <span style={{
                      padding: '2px 8px',
                      borderRadius: '4px',
                      fontSize: '12px',
                      backgroundColor: task.priority === 'critical' ? '#ffebee' : 
                                     task.priority === 'high' ? '#fff3e0' : '#e8f5e9'
                    }}>
                      {task.priority}
                    </span>
                  </td>
                  <td style={tdStyle}>{task.status}</td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>

      {/* Recent Messages */}
      <div>
        <h3>💬 Recent Agent Messages</h3>
        {messages.length === 0 ? (
          <p>No messages yet</p>
        ) : (
          <div style={{ maxHeight: '400px', overflowY: 'auto' }}>
            {messages.slice(-20).reverse().map(msg => (
              <div key={msg.id} style={{
                border: '1px solid #eee',
                borderRadius: '4px',
                padding: '10px',
                marginBottom: '8px',
                backgroundColor: msg.messageType === 'alert' ? '#ffebee' : '#f9f9f9'
              }}>
                <div style={{ fontSize: '12px', color: '#666', marginBottom: '5px' }}>
                  <strong>{msg.fromAgent}</strong> ({msg.role}) 
                  {msg.toAgent ? ` → ${msg.toAgent}` : ' (broadcast)'} • 
                  {new Date(msg.timestamp).toLocaleTimeString()}
                </div>
                <div>{msg.content}</div>
                {msg.taskId && (
                  <div style={{ fontSize: '11px', color: '#999', marginTop: '5px' }}>
                    Task: {msg.taskId}
                  </div>
                )}
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

const thStyle = {
  padding: '10px',
  textAlign: 'left' as const,
  borderBottom: '2px solid #ddd'
};

const tdStyle = {
  padding: '10px',
  borderBottom: '1px solid #eee'
};

// Update main component to include Multi-Agent tab
// Find the tabs section and add new tab
